from pathlib import PurePath, Path
# p=PurePath("f:/pylab/L5/a.py")
# # print(p)
# # print(p.name)
# # print(p.suffix)
# # print(p.parent)
# p=PurePath().joinpath('f:','pylab','L5','b.py')
# print(p)
# p=Path("text.txt")
# print(p.exists())
# print(p.is_dir())
# print(p.is_file())
# print(p)
base_dir=Path('.').absolute()  # Current Absolute Path (dir)
# print(base_dir.absolute())
file=(base_dir / 'test3.txt')
# base_dir=Path('F:\\pylab\\PythonBestPractices\\L5')
# print(base_dir.relative_to('f:\\pylab'))
# file_p=base_dir /'PythonBestPractices' / 'file.txt'
# file_p.joinpath('f:','PythonBestPractices' , 'file.txt')
#print(file_p.absolute())
print(file)
file.write_text('testing module Path',encoding="utf-32")
print(file.read_text(encoding="utf-32"))
